config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"


  resources :products, only: %i[new create index show] do
    resources :orders, only: [ :new, :create ]
  end

  resources :users do
    resources :orders, only: %i[index show]
  end

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :quantity, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :name, :unit_price, :quantity, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_city_and_name,
    against: :name,
    associated_against: { user: :city },
    using: {
      tsearch: { prefix: true }
    }
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :products

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :city])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :city])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = current_user.orders
  end

  def new
    @order = Order.new
  end

  def show
    @order = Order.find(params[:id])
  end

  # def create
  #   @order = Order.new(product_params)
  #   @order.user = current_user
  #   @order.save
  #   redirect_to root_path
  # end

  def create
    @product = Product.find(params[:product_id])
    @order = Order.new(order_params)
    @order.product = @product
    @order.user = current_user
    if @product.quantity == 0
      redirect_to product_path(@product), notice: 'Product not available.'
    elsif @order.quantity > @product.quantity
      redirect_to product_path(@product), notice: 'Quantity not available.'
    else
      old_product_quantity = @product.quantity
      @product.quantity = old_product_quantity - @order.quantity
      @product.save
      @order.save
      redirect_to product_path(@product), notice: 'Order was successfully created.'
    end
  end

  private
  def order_params
    params.require(:order).permit(:quantity, :product_id)
  end
  # private
  # def order_params
  #   params.require(:order).permit(:name, :unit_price, :quantity, :description)
  # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @products = Product.search_by_city_and_name(params[:query])
    else
      @products = Product.all
    end

      #  sql_query = " \
      #   movies.title ILIKE :query \
      #   OR movies.synopsis ILIKE :query \
      #   OR directors.first_name ILIKE :query \
      #   OR directors.last_name ILIKE :query \
      # "
      # @users = User.joins(:product).where(sql_query, query: "%#{params[:query]}%")

      #@users = @products.map { |product| product.user }.uniq
      #@users = User.joins(:products).where(products:{"name ILIKE ?", "%#{params[:query]}%"})
      #@users = User.joins("SELECT * FROM users JOIN products ON users.id = products.user_id;")
      @users =  User.where(id: @products.map(&:user_id))

      @markers = @users.geocoded.map do |user|
        {
          lat: user.latitude,
          lng: user.longitude,
          info_window: render_to_string(partial: "info_window", locals: { user: user })
        }
      end
  end

  def show
    @product = Product.find(params[:id])
    @user = User.find(@product.user_id)
    @order = Order.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    address = "#{current_user.address}, #{current_user.city}"
    new_coordinates = Geocoder.coordinates(address)

    unless new_coordinates.nil?
      # current_user.longitude =
      # current_user.latitude = new_coordinates[0]
      # current_user.save
      user = User.find(current_user.id)
      user.latitude = new_coordinates[0]
      user.longitude = new_coordinates[1]
      user.save!
    else
      new_coordinates = Geocoder.coordinates(current_user.city)
      user = User.find(current_user.id)
      user.latitude = new_coordinates[0]
      user.longitude = new_coordinates[1]
      user.save!
    end

    @product.user = current_user
    if @product.save
      redirect_to root_path, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :unit_price, :quantity, :description, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XepaDaLajeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="index-container">
    <%= yield %>
    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<h2>My Orders</h2>

<% @orders.each do |order| %>
  <p><%=order.product.name%> - $<%=order.product.unit_price%> - <%=order.quantity%> - <%=order.created_at.strftime("%d/%m/%Y")%> </p>
<%end%>
<%=link_to "Back", :back%>

app/views/orders/show.html.erb
<h1><%= @order.id %></h1>
<p><%=@order.user.email%></p>
<p><%=@order.product.name%></p>
<p><%=@order.quantity%></p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= form_tag products_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a product"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/products/_info_window.html.erb
<p class="text-left">
  <strong>Products</strong>
  <br>
  <% products = Product.where(user_id: user) %>
  <%products.each do |product|%>
    <%=link_to product.name.capitalize, product_path(product)%>
  <%end%>
</p>

app/views/products/index.html.erb
<div class="main-card mt-2 mb-2 text-center pt-4 rounded-0" style="width: 100%; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/photos/demolition-rubble-picture-id157637703?b=1&k=20&m=157637703&s=170667a&w=0&h=ClTovdBmulqBTy9nSje4xtXSjFpyqm6kfMxZfnLs5w4=)">
  Choose your construction trash!
</div>
<div id="map" class=""
     style="width: 100%; height: 250px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<% @products.each do |product| %>
 <div class="card-product d-flex justify-content-between align-items-center">
 <div class="d-flex align-items-center">
 <% if product.photo.key%>
  <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
  <%else%>
  <img class="ml-3" src="https://images.unsplash.com/photo-1547056961-3c25e9140b05?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YnJpY2tzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60" />
  <%end%>
    <div class="product-description ml-2 p-2 text-left align-items-center">
      <h2 class="product-name"><%=product.name%></h2>
      <p>Unit: <strong>$<%=product.unit_price%></strong> - City: <strong><%=product.user.city.capitalize%></strong></p>
      <p><%=product.description%></p>
    </div>
</div>
    <%=link_to "Buy!", product_path(product), class: "btn btn-success m-4"%>
  </div>
<%end%>

app/views/products/new.html.erb
<div class="title text-center m-2"><h3>Sell your construction trash!</h3></div>

<div class="container-form d-flex justify-content-center text-center">
  <div class="form-new-product text-center pb-4">
    <%= simple_form_for(@product) do |f| %>

    <div class="form-group justify-content-center">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
    </div>

    <div class="form-group justify-content-center">
      <%= f.label :unit_price %>
      <br>
      <%= f.text_field :unit_price %>
    </div>

    <div class="form-group justify-content-center">
      <%= f.label :quantity %>
      <br>
      <%= f.text_field :quantity %>
    </div>

    <div class="form-group justify-content-center">
      <%= f.label :description %>
      <br>
      <%= f.text_field :description%>
    </div>

    <div class="form-group justify-content-center">
      <%= f.input :photo, as: :file %>
    </div>

    <%= f.button :submit, "Sell product", class: "btn btn-success text-center" %>
   <% end %>
     <%=link_to "Back", :back, class: "btn btn-danger text-center mt-3"%>
  </div>
</div>

app/views/products/show.html.erb
<h1 class="text-center">Buy <%= @product.name %>! </h1>

<%# <div class="card-product-show"> %>
<div class="container-form text-center d-flex justify-content-center p-4">

  <%# # card-product-infos-show %>

  <div class="form-login text-center mr-1">
    <% if @product.photo.key%>
      <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>
    <%else%>
      <img class="mw-100" src="https://images.unsplash.com/photo-1547056961-3c25e9140b05?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YnJpY2tzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60" />
    <%end%>
  </div>
  <div class="form-login text-center">
    <p>Unit price: <%=@product.unit_price%></p>
    <p>Quantity: <%=@product.quantity%></p>
    <p>Description: <%=@product.description%></p>
    <p>Seller: <%=@product.user.email%></p>
    <div>
      <%= simple_form_for @order, url:product_orders_path(@product.id,current_user) do |f| %>
        <%= f.input :quantity, required: true %>
        <div class="text-center">
          <% if user_signed_in? && (current_user != @user)%>
            <%= f.button :submit, value: "Buy!", class: "btn btn-success m-4" %>
          <% elsif user_signed_in? == false %>
            <%=link_to "Sign in to buy!", new_user_session_path, class: "btn btn-success m-4"%>
          <%end%>
      <% end %>
      <%=link_to "Back", root_path, class: "btn btn-danger m-4"%>
    </div>
  </div>
</div>

</div>


<%# <div class="text-center">
<%=link_to "Back", :back, class: "btn btn-danger m-4"%>
<%# <% if user_signed_in? && (current_user != @user) %>
  <%# <%=link_to "Buy!", product_orders_path(@product,current_user), method: :post, class: "btn btn-success m-4"%>
<%# <% elsif user_signed_in? == false %>
  <%# <%=link_to "Sign in to buy!", new_user_session_path, class: "btn btn-success m-4"%>
<%# <%end%>
<%# </div> %>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/pjfernandes/xepa-da-laje-app/"><i class="fab fa-github"></i></a>
    <%# <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a> %>
  </div>
  <div class="footer-copyright">
    By Luis, Marcelo, Pedro & Tatiane at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon m-6 fixed-top">

  <div class="logo d-flex justify-content-between">
  <%= image_tag "logo2.png",size:57%>
    <div class="xepa text-left ml-2 mt-3 pb-2 d-flex align-items-center">
      <h2>Xepa da Laje</h2>

    </div>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
         <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "user_icon.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Sell", "products/new", class: "dropdown-item" %>
            <%= link_to "My orders", user_orders_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit my profile ", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<%# <%=link_to "Buy!", new_product_order_path(@product)%>